name: CansteinGottesdienst
version: '${project.version}'
main: net.quickwrite.cansteingottesdienst.CansteinGottesdienst
api-version: 1.17
authors: [ QuickWrite, Hasenzahn1 ]

depend: [ WorldGuard ]

commands:
  rlgl:
    description: "RLGL"
    usage: /rlgl <start/stop/setup>
  customblock:
    description: "CustomBlock commands"
    usage: /customblock [get|remove] <id>
  cdebug:
    description: "Debug commands for this plugin (only for developers)"
    usage: /cdebug