name: CansteinGottesdienst
version: '${project.version}'
main: net.quickwrite.cansteingottesdienst.CansteinGottesdienst
api-version: 1.17
authors: [ QuickWrite, Hasenzahn1 ]

depend: [ WorldGuard ]

commands:
  rlgl:
    description: "RLGL"
    usage: /rlgl <start/stop/setup>
  getCustomBlock:
    description: "Get a custom block"
    usage: /getCustomBlock <id>