name: CansteinGottesdienst
version: '${project.version}'
main: net.quickwrite.cansteingottesdienst.CansteinGottesdienst
api-version: 1.17
authors: [ QuickWrite, Hasenzahn1 ]

depend: [ WorldGuard ]

commands:
  rlgl:
    description: "RLGL"
    usage: "/rlgl <start/stop/setup>"
  customblock:
    description: "CustomBlock commands"
    usage: "/customblock [get|remove] <id>"
  initmap:
    description: "Debug commands for this plugin (only for developers)"
    usage: "/initmap"
  customItem:
    description: "CustomItem commands"
    usage: "/customItem <id>"
  pmsgPlayer:
    description: "Sends messages as another entity to one other player"
    usage: "/pmsgPlayer <name> <message>"
  pmsgAllPlayersWithTheirName:
    description: "Sends messages as another entity every other player"
    usage: "/pmsgAllPlayersWithTheirName <name> <message>"
  pmsglobal:
    description: "Sends messages as another entity to all players"
    usage: "/pmsglobal <name> <message>"
  setupmap:
    description: "Command to set up the map"
    usage: "/setupmap"
  trackermap:
    description: "Gives you (or another player) a TrackerMap."
    usage: "/trackermap get <Player|all>"