name: CansteinGottesdienst
version: '${project.version}'
main: net.quickwrite.cansteingottesdienst.CansteinGottesdienst
api-version: 1.17
authors: [ QuickWrite, Hasenzahn1 ]

depend: [ WorldGuard ]

commands:
  rlgl:
    description: "RLGL"
    usage: "/rlgl <start/stop/setup>"
  customblock:
    description: "CustomBlock commands"
    usage: "/customblock [get|remove] <id>"
  cdebug:
    description: "Debug commands for this plugin (only for developers)"
    usage: "/cdebug"
  customItem:
    description: "CustomItem commands"
    usage: "/customItem <id>"
  pmsg:
    description: "Sends messages as another entity"
    usage: "/pmsg <name> <message>"
  trackermap:
    description: "Gives you (or another player) a TrackerMap."
    usage: "/trackermap get <Player|all>"